In [1]:
def test():
    print("Test() for function")
    return
test()

Test() for function


In [2]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [4]:
class Demo1:
    def fact(self,n):
        #return the factorial
        return
p1=Demo1()
p1.fact(5)#120

In [8]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
    
p1=Demo1()
print(p1.fact(8))

40320


In [10]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
        
        
c1=Demo2(10,20)
print(c1.add(750,250))

1000


In [2]:
class person():
    #constrution
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isEmployee(self):
        return False
    
#Derived class
class Employee(person):
    def isEmployee(self):
        return True
    
emp=person("anil")
print(emp.getname(),emp.isEmployee())

emp1=Employee("manish")
print(emp1.getname(),emp1.isEmployee())

anil False
manish True


# Python Numpy

In [6]:
import numpy as np
lst=[1,2,3,4,5]
array=np.array(lst)
print(array)

[1 2 3 4 5]


In [7]:
lst=[1,2,3,4,5]
array=np.array(lst)
array+10

array([11, 12, 13, 14, 15])

In [8]:
lst=[1,2,3,4,5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(5,)
int32


In [9]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(4,5,6),(3,2,1)])
print(a2.shape)

(2, 3)
(2, 3)


In [11]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
#np.ones(shape,dtype=float,order="c")
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [16]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [17]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[2]=5
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [18]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[1][3]=5
np.asarray(a)[3][3]=23
print(a)

[[ 1  1  1  1]
 [ 1  1  1  5]
 [ 1  1  1  1]
 [ 1  1  1 23]]


In [19]:
# Indexing and slicing of numpy 
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [20]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])


first row: [1 2 3]


In [26]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[5.06750304 3.23881681 4.73349158 5.35221843 4.60721002 5.07722942
 4.68088154 4.61354706 3.60328141 4.21632801]
min value= 3.2388168067220837
max value= 5.352218426440479
mean value= 4.519050731437588
median value= 4.647214302300917


In [4]:
c1 = np.array([1,2])
c2 = np.array([4,5])
np.dot(c1,c2)

14

In [5]:
c1 = np.array([(1,2),(3,4)])
c2 = np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])